"""
Sync Service – pushes pending local changes to the cloud PostgreSQL database.

Algorithm
---------
1. Load all unsynced local sync_log rows.
2. Query cloud SyncLogs for any IDs that already exist (a previous partial push).
3. For each new entry:
   a. Apply the data change to the relevant cloud table (INSERT / UPDATE / DELETE).
   b. Mirror the sync_log row into cloud SyncLogs so both sides stay consistent.
   c. Mark the local row as synced.
4. On error, record the error in the local sync_log row and continue.
"""

import asyncio
import json
import uuid as _uuid_mod

import psycopg2
import psycopg2.extras

from Database.orm_models import SyncLog
from Database.orm_session import get_session
from Database.models import utc_now as _utc_now
from Database.sync_log import SyncAction
from Services.pg_config import LOCAL_TO_PG_TABLE, PG_CONFIG, snake_to_pascal

# Register psycopg2 UUID adapter so uuid.UUID objects are sent as PG uuid type
psycopg2.extras.register_uuid()

# Cloud SyncLogs."Action" column is stored as integer (EF Core enum mapping)
_ACTION_INT = {
    "INSERT":      1,
    "UPDATE":      2,
    "SOFT_DELETE": 3,
    "HARD_DELETE": 4,
}


def _as_uuid(value):
    """Return a uuid.UUID if *value* is a valid UUID string, otherwise return it unchanged."""
    if isinstance(value, str):
        try:
            return _uuid_mod.UUID(value)
        except ValueError:
            pass
    return value


def _prepare_row(mapping: dict) -> dict:
    """Convert any UUID-shaped string values to uuid.UUID objects for psycopg2 adaptation.
    Also converts int 0/1 to Python bool for columns that map to PG boolean,
    and strips RowVersion (DB-generated by EF Core, not a regular INSERT column).
    """
    _BOOL_COLS = frozenset({
        "Authorized", "IsDeleted", "IsSystemFeature", "IsEnabled",
        "IsSystemRole", "IsGroup", "IsRegistered", "IsCreditAllowed",
        "IsActive", "IsSynced", "CanCreate", "CanRead", "CanUpdate",
        "CanDelete", "CanAuthorize",
    })
    result = {}
    for k, v in mapping.items():
        if k == "RowVersion":
            continue  # DB-generated by EF Core; never part of an INSERT payload
        if k in _BOOL_COLS and isinstance(v, int):
            v = bool(v)
        else:
            v = _as_uuid(v)
        result[k] = v
    return result


class SyncService:
    """Static async helpers – mirrors PullService structure for UI integration."""

    # ── Public async entry-point ──────────────────────────────────────────────

    @staticmethod
    async def push_to_cloud(progress_callback=None):
        """Run the blocking push in a thread executor so the UI stays responsive.

        Returns:
            (success: bool, message: str)
        """
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None, SyncService._sync_push_to_cloud, progress_callback
        )

    # ── Blocking implementation ───────────────────────────────────────────────

    @staticmethod
    def _sync_push_to_cloud(progress_callback=None):
        def _progress(msg):
            if progress_callback:
                progress_callback(msg)

        pg_conn = None
        try:
            with get_session() as session:
                from sqlalchemy import select as _sa_select

                pending = (
                    session.execute(
                        _sa_select(SyncLog)
                        .where(SyncLog.is_synced == 0)
                        .order_by(SyncLog.created_on)
                    )
                    .scalars()
                    .all()
                )
                if not pending:
                    return True, "Nothing to push – all changes are up to date."

                _progress(f"Found {len(pending)} pending change(s). Connecting to cloud…")
                pg_conn = psycopg2.connect(**PG_CONFIG)
                pg_cursor = pg_conn.cursor()

                success = 0
                errors = 0
                error_details: list[str] = []

                for log_obj in pending:
                    try:
                        # Per-entry idempotency check: if this sync log ID already
                        # exists in the cloud SyncLogs table the data was already
                        # applied – just mark it synced locally without re-applying.
                        pg_cursor.execute(
                            'SELECT 1 FROM "SyncLogs" WHERE "Id" = %s',
                            (_as_uuid(log_obj.id),),
                        )
                        if pg_cursor.fetchone():
                            log_obj.is_synced = 1
                            log_obj.synced_on = _utc_now()
                            session.commit()
                            success += 1
                            _progress(
                                f"  ↷ Already in cloud – skipped "
                                f"{log_obj.table_name} ({log_obj.record_id[:8]}…)"
                            )
                            continue

                        # Not yet in cloud SyncLogs → apply data change then log it.
                        SyncService._apply_to_postgres(pg_cursor, log_obj)
                        SyncService._insert_cloud_sync_log(pg_cursor, log_obj)
                        pg_conn.commit()
                        log_obj.is_synced = 1
                        log_obj.synced_on = _utc_now()
                        session.commit()
                        success += 1
                        _progress(
                            f"  ✓ {log_obj.action} {log_obj.table_name} "
                            f"({log_obj.record_id[:8]}…)"
                        )
                    except Exception as exc:
                        pg_conn.rollback()
                        log_obj.sync_error = str(exc)
                        log_obj.retry_count = (log_obj.retry_count or 0) + 1
                        session.commit()
                        errors += 1
                        error_details.append(
                            f"{log_obj.action} {log_obj.table_name} "
                            f"({log_obj.record_id[:8]}…): {exc}"
                        )
                        _progress(f"  ✗ {log_obj.action} {log_obj.table_name}: {exc}")

                if errors:
                    detail_str = "\n".join(error_details)
                    return (
                        False,
                        f"Push complete: {success} succeeded, {errors} failed.\n\n"
                        f"Errors:\n{detail_str}",
                    )
                return True, f"Push complete: {success} change(s) pushed to cloud."

        except Exception as exc:
            return False, f"Push failed: {exc}"
        finally:
            if pg_conn:
                pg_conn.close()

    # ── Internal helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _apply_to_postgres(pg_cursor, log_obj: SyncLog):
        """Translate one local sync_log entry into a PostgreSQL statement."""
        local_table = log_obj.table_name
        record_id   = log_obj.record_id
        action      = log_obj.action
        changed_data = (
            json.loads(log_obj.changed_data) if log_obj.changed_data else {}
        )

        # Map local snake_case table name → cloud PascalCase table name
        pg_table = LOCAL_TO_PG_TABLE.get(local_table, snake_to_pascal(local_table) + "s")
        uid = _as_uuid(record_id)

        if action == SyncAction.INSERT:
            # changed_data is flat {snake_col: value}
            pg_cols = _prepare_row({snake_to_pascal(k): v for k, v in changed_data.items()})
            cols_sql     = ", ".join(f'"{c}"' for c in pg_cols)
            placeholders = ", ".join(["%s"] * len(pg_cols))
            pg_cursor.execute(
                f'INSERT INTO "{pg_table}" ({cols_sql}) VALUES ({placeholders}) '
                f'ON CONFLICT ("Id") DO NOTHING',
                list(pg_cols.values()),
            )

        elif action == SyncAction.UPDATE:
            # changed_data format: {snake_col: {"old": x, "new": y}}
            raw = {}
            for k, v in changed_data.items():
                new_val = v["new"] if isinstance(v, dict) and "new" in v else v
                raw[snake_to_pascal(k)] = new_val
            updates = _prepare_row(raw)
            set_clause = ", ".join(f'"{col}" = %s' for col in updates)
            pg_cursor.execute(
                f'UPDATE "{pg_table}" SET {set_clause} WHERE "Id" = %s',
                list(updates.values()) + [uid],
            )

        elif action == SyncAction.SOFT_DELETE:
            pg_cursor.execute(
                f'UPDATE "{pg_table}" SET "IsDeleted" = true, "DeletedBy" = %s, '
                f'"DeletedOn" = %s WHERE "Id" = %s',
                (
                    changed_data.get("deleted_by", ""),
                    changed_data.get("deleted_on"),
                    uid,
                ),
            )

        elif action == SyncAction.HARD_DELETE:
            pg_cursor.execute(
                f'DELETE FROM "{pg_table}" WHERE "Id" = %s',
                (uid,),
            )

    @staticmethod
    def _insert_cloud_sync_log(pg_cursor, log_obj: SyncLog):
        """Mirror the local sync_log row into the cloud SyncLogs table."""
        action_int = _ACTION_INT.get(log_obj.action, log_obj.action)
        pg_cursor.execute(
            """
            INSERT INTO "SyncLogs"
                ("Id", "TableName", "RecordId", "Action", "ChangedData",
                 "IsSynced", "RetryCount")
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT ("Id") DO NOTHING
            """,
            (
                _as_uuid(log_obj.id),
                log_obj.table_name,
                _as_uuid(log_obj.record_id),
                action_int,
                log_obj.changed_data,
                True,
                log_obj.retry_count or 0,
            ),
        )
